Added prototype for the BERT deseralizer
Relrin/bert-rs pull request #4
Opened 2016-09-03 11:31 UTC by Relrin

2016-09-06 16:32 UTC, dtolnay commented
[Serde 0.8.7](https://github.com/serde-rs/serde/releases/tag/v0.8.7) provides its own `forward_to_deserialize!` macro so you don't need to copy forward.rs. [Here is example usage from serde_json](https://github.com/serde-rs/json/pull/148/files).

2016-09-06 17:46 UTC, Relrin commented
Thanks for this proposal. It looks very helpful for me 👍

2016-10-12 08:02 UTC, oli-obk requested changes
I was wrong. You don't need a second `Visitor`, but a `Deserializer` whose sole purpose is to deserialize BigNum

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +    de: &'a mut Deserializer<R>,
remove these fields. This Visitor should not have state.

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +    fn visit_newtype_struct<D>(&mut self, _: &mut D) -> StdResult<BertBigInteger, D::Error>
don't ignore the deserializer, use it, don't pass the deserializer through a field.

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +        deserializer.deserialize_newtype_struct(
just call `deserializer.deserialize(BertBigNumberVisitor)`

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +        let n = match self.header {
You should not be accessing the deserializer directly. Instead, use `Deserialize::deserialize` calls to obtain the correct value, in this case, `let v: Vec<u8> = Deserialize::deserialize(deserializer)`

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +        visitor.visit_newtype_struct(BertBigNumberVisitor::new(self, header))
Here you need to pass `BertBigNumberDeserializer::new(self, header)`.

2016-10-12 08:02 UTC, oli-obk commented on bert/src/deserializers.rs
> +        Ok(BertBigInteger(bigint))
just do `let v: Vec<u8> = try!(Deserializer::deserialize(deserializer)); and then do all the above code code inside `BertBigNumberDeserializer`.

2016-10-16 10:49 UTC, Relrin commented on bert/src/deserializers.rs
> +        visitor.visit_newtype_struct(BertBigNumberVisitor::new(self, header))
I don't quite understand what is the `BertBigNumberDeserializer::new(self, header)`. Maybe you mean BertBigNumberVisitor there? As far as I remember, for each custom type we must to implement `Deserialize` and `Visitor` traits for the concrete type which we want to deserialize in the result, isn't it? Perhaps you me mean to implement similar deserializer like default and use it?

2016-10-16 11:27 UTC, Relrin commented on bert/src/deserializers.rs
> +        visitor.visit_newtype_struct(BertBigNumberVisitor::new(self, header))
And yet another question. This suggestion too much different from a suggestions which described in the Serde docs (like [this](https://serde.rs/deserialize-map.html)).
@dtolnay Why this approaches too different from the documentation? In my case only what I need is just read few bytes (in the worst case few bytes additionally) and put all this values into `num::bigint::BigInt` structure. Occasionally, it makes me thing that we doing too much actions to make a simple task.
In compare with Serde serializers functionality deserializers look too complex and harder in maintenance in further. That big differences (sometimes too much) just blows my mind :(

2016-11-11 19:45 UTC, closed without merging